# Generated by Django 4.2.7 on 2025-10-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
    ]
