# Generated by Django 4.2.7 on 2025-10-03 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('urology', 'Urology'), ('other', 'Other')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=200)),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated languages', max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', 'user__first_name'],
            },
        ),
    ]
