# Generated by Django 4.2.7 on 2025-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='years_of_experience',
            new_name='experience_years',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('urology', 'Urology'), ('other', 'Other')], max_length=50),
        ),
    ]
